name: continuous-deployment
on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!**.md"
  pull_request:
    paths:
      - "**"
      - "!**.md"
env:
  PACKAGE_NAME: 'ghcr.io/archi-tektur/caddy-php'
  PACKAGE_VERSION: '2.2.0'
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: archi-tektur
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set Git user
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@github.com'

      - name: Clone Git repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ env.PACKAGE_NAME}}:${{ env.PACKAGE_VERSION }} .

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Publish Docker images
        run: docker push ${{ env.PACKAGE_NAME}}:${{ env.PACKAGE_VERSION }}

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Publish version
        run: git tag ${{ env.PACKAGE_VERSION }} && git push && git push --tags
