name: "test"
on:
  pull_request:
    paths: [ "**", "!**.md" ]
jobs:
  test:
    runs-on: "ubuntu-22.04"
    steps:
      - { name: "Login to GitHub Container Registry", uses: "docker/login-action@v2", with: { registry: "ghcr.io", username: "at-cloud-pro", password: "${{secrets.GITHUB_TOKEN}}" } }
      - { name: "Clone Git repository", uses: "actions/checkout@v3" }
      - { name: "Build Docker image",  run: "docker build ." }
